# Generated by Django 5.2.7 on 2026-01-20 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='map_embed',
            field=models.TextField(blank=True, help_text='Google Maps embed code (iframe)'),
        ),
    ]
