# Generated by Django 5.2.7 on 2026-01-20 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0004_set_existing_properties_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_name', models.CharField(max_length=255)),
                ('buyer_email', models.EmailField(blank=True, max_length=254)),
                ('buyer_phone', models.CharField(blank=True, max_length=50)),
                ('bedrooms_min', models.PositiveIntegerField(default=0)),
                ('bedrooms_max', models.PositiveIntegerField(blank=True, null=True)),
                ('budget_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('budget_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(default='EUR', max_length=10)),
                ('location_city', models.CharField(blank=True, max_length=255)),
                ('location_area', models.CharField(blank=True, max_length=255)),
                ('property_type', models.CharField(blank=True, choices=[('APARTMENT', 'Apartment'), ('HOUSE', 'House'), ('VILLA', 'Villa'), ('COMMERCIAL', 'Commercial')], max_length=20)),
                ('parking_required', models.BooleanField(default=False)),
                ('balcony_required', models.BooleanField(default=False)),
                ('furnished_required', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('FULFILLED', 'Fulfilled')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Buyer Search',
                'verbose_name_plural': 'Buyer Searches',
                'ordering': ['-created_at'],
            },
        ),
    ]
